apiVersion: v1
kind: Pod
metadata:
  name: deployment
  labels:
    app: deployment
spec:
  containers:
    - name: fiap-tech-challenge
      image: 'tech-challenge:latest'
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          value: myuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: secret
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: update